### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by 0908727527**
I added Vietnamese, sorry my bad Eng :) Thanks!!!

### CODE REVIEW

**Comment by LaughingQuoll** [comment]
Is this a full translation. "Dark Mode" does not seem to be translated. Will merge when confirmed.

**Comment by 0908727527** [comment]
Keep it in english because it sounds weird if I translate it to vietnamese lol. I already edited the translated file

**Comment by LaughingQuoll** [comment]
Merged.

**Comment by 0908727527** [comment]
please help me correct to vi.lproj. Thank for talking time to help.

**Pull request merged**
